# -*- coding: utf-8 -*-
"""detections.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsfzEg5CjcdwAIIkGwXS0b-Bj13FhwfA
"""

import pandas as pd

# Load detections
df = pd.read_csv("detections.csv")

# Classes you want for the shopping website
selected_classes = [
    "chair",
    "tie",
    "umbrella",
    "cup",
    "bottle",
    "tv",
    "book",
    "laptop",
    "cell phone",
    "handbag",
    "vase",
    "suitcase",
    "remote",
    "wine glass",
    "bowl",
    "teddy bear",
    "skateboard",
    "skis",
    "surfboard"
]

# Keep only shopping-related objects
df = df[df["label"].isin(selected_classes)]

# Categories
category_map = {
    "chair":"Furniture",
    "tie":"Fashion",
    "umbrella":"Accessories",
    "cup":"Kitchen",
    "bottle":"Kitchen",
    "tv":"Electronics",
    "book":"Books",
    "laptop":"Electronics",
    "cell phone":"Electronics",
    "handbag":"Fashion",
    "vase":"Home Decor",
    "suitcase":"Travel",
    "remote":"Electronics",
    "wine glass":"Kitchen",
    "bowl":"Kitchen",
    "teddy bear":"Toys",
    "skateboard":"Sports",
    "skis":"Sports",
    "surfboard":"Sports"
}

df["category"] = df["label"].map(category_map)

df.to_csv("categorized_detections.csv", index=False)

print("Saved categorized_detections.csv")
print(df["label"].value_counts())

import pandas as pd

df = pd.read_csv("categorized_detections.csv")

product_map = {
    "chair": "Ergonomic Office Chair",
    "tie": "Premium Silk Tie",
    "umbrella": "Travel Umbrella",
    "cup": "Ceramic Coffee Mug",
    "bottle": "Hydro Flask Bottle",
    "tv": "Samsung Smart TV",
    "wine glass": "Crystal Wine Glass Set",
    "book": "Business Strategy Book",
    "bowl": "Ceramic Bowl Set",
    "laptop": "MacBook Air",
    "cell phone": "iPhone 15",
    "remote": "Universal Remote",
    "suitcase": "Travel Suitcase",
    "handbag": "Leather Handbag",
    "vase": "Decorative Vase",
    "skateboard": "Street Skateboard",
    "teddy bear": "Plush Teddy Bear",
    "skis": "All-Mountain Skis",
    "surfboard": "Beginner Surfboard"
}

price_map = {
    "chair": 149,
    "tie": 29,
    "umbrella": 24,
    "cup": 12,
    "bottle": 35,
    "tv": 699,
    "wine glass": 45,
    "book": 15,
    "bowl": 20,
    "laptop": 999,
    "cell phone": 799,
    "remote": 25,
    "suitcase": 89,
    "handbag": 79,
    "vase": 30,
    "skateboard": 120,
    "teddy bear": 18,
    "skis": 450,
    "surfboard": 350
}

df["product_name"] = df["label"].map(product_map)
df["price"] = df["label"].map(price_map)

df.to_csv("predictions.csv", index=False)

print("predictions.csv created")
print(df.head())

import pandas as pd

df = pd.read_csv("predictions.csv")

df.to_json(
    "predictions.json",
    orient="records",
    indent=2
)

print("predictions.json created")

