# -*- coding: utf-8 -*-
"""yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIdrBtSOUVp74VybTBYM0otiyIRP9NOl
"""

import os

files = os.listdir('/content')
print("Total files:", len(files))
print(files[:10])  # show first 10 files

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

!unzip frame_00001.zip -d frames

import os

print(len(os.listdir("frames")))

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

!unzip frame_00001.zip -d frames

import os

print("Total frames:", len(os.listdir("frames")))
print(os.listdir("frames")[:5])

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

results = model.predict(
    source="frames",
    save=True,
    conf=0.3
)

import os
print(os.listdir("runs/detect"))

from IPython.display import Image

Image("/content/runs/detect/predict/frame_00001.jpg")

import pandas as pd
import os
from ultralytics import YOLO

model = YOLO("yolov8s.pt")

rows = []

for img in sorted(os.listdir("frames")):
    path = os.path.join("frames", img)

    results = model(path)

    for r in results:
        for box in r.boxes:

            cls = int(box.cls[0])
            label = model.names[cls]

            conf = float(box.conf[0])

            x1,y1,x2,y2 = box.xyxy[0].tolist()

            rows.append([
                img,
                label,
                conf,
                x1,y1,x2,y2
            ])

df = pd.DataFrame(
    rows,
    columns=[
        "frame",
        "label",
        "confidence",
        "x1","y1","x2","y2"
    ]
)

df.to_csv("detections.csv", index=False)

print(df.head())

import pandas as pd

df = pd.read_csv("detections.csv")

print(df.head())
print(df.shape)

import pandas as pd

df = pd.read_csv("detections.csv")

print(df.head())
print(df.columns)
print(df.shape)

print(df["label"].value_counts())

import pandas as pd

df = pd.read_csv("detections.csv")

SHOPPABLE_CLASSES = [
    "chair",
    "tie",
    "umbrella",
    "cup",
    "bottle",
    "laptop",
    "cell phone",
    "handbag",
    "book",
    "tv"
]

filtered = df[df["label"].isin(SHOPPABLE_CLASSES)]

print(filtered.shape)

filtered.to_csv(
    "filtered_detections.csv",
    index=False
)

category_map = {
    "chair": "Furniture",
    "tie": "Fashion",
    "umbrella": "Accessories",
    "cup": "Kitchen",
    "bottle": "Kitchen",
    "laptop": "Electronics",
    "cell phone": "Electronics",
    "handbag": "Fashion",
    "book": "Books",
    "tv": "Electronics"
}

filtered["category"] = filtered["label"].map(category_map)

filtered.to_csv(
    "categorized_detections.csv",
    index=False
)

products = pd.DataFrame([
    ["chair","Furniture","Ergonomic Chair",149],
    ["tie","Fashion","Silk Tie",29],
    ["umbrella","Accessories","Travel Umbrella",24],
    ["cup","Kitchen","Coffee Mug",12],
    ["bottle","Kitchen","Hydro Flask",35],
    ["laptop","Electronics","MacBook Air",999],
    ["cell phone","Electronics","iPhone 15",799],
    ["handbag","Fashion","Leather Handbag",89],
    ["book","Books","Business Book",15],
    ["tv","Electronics","Samsung Smart TV",699]
], columns=[
    "label",
    "category",
    "product_name",
    "price"
])

products.to_csv("products.csv", index=False)

detections = pd.read_csv("categorized_detections.csv")
products = pd.read_csv("products.csv")

predictions = detections.merge(
    products,
    on=["label","category"],
    how="left"
)

predictions.to_csv(
    "predictions.csv",
    index=False
)

import pandas as pd

df = pd.read_csv("detections.csv")

selected_classes = [
    "chair",
    "tie",
    "umbrella",
    "cup",
    "bottle",
    "tv",
    "book",
    "laptop",
    "cell phone",
    "handbag",
    "vase",
    "suitcase",
    "remote",
    "wine glass",
    "bowl",
    "teddy bear",
    "skateboard",
    "skis",
    "surfboard"
]

filtered = df[df["label"].isin(selected_classes)]

filtered.to_csv("filtered_detections.csv", index=False)

print(filtered["label"].value_counts())

